from django.urls import path
from . import views

urlpatterns = [
    path('', views.std_login, name='std_login'),
    path('my/', views.myJenjangs, name='myJenjangs'),
    path('pengasuhJenjangs/', views.pengasuhJenjangs, name='pengasuhJenjangs'),
    path('login/', views.std_login, name='std_login'),
    path('logout/', views.std_logout, name='std_logout'),
    path('my/<int:code>/', views.jenjang_page, name='jenjang'),
    path('profile/<str:id>/', views.profile, name='profile'),
    path('pengasuhProfile/<str:id>/', views.profile, name='profile_pengasuh'),
    path('pengasuh/<int:code>/', views.jenjang_page_pengasuh, name='pengasuh'),
    path('addAnnouncement/<int:code>/',
         views.addAnnouncement, name='addAnnouncement'),
    path('announecement/<int:code>/<int:id>/',
         views.deleteAnnouncement, name='deleteAnnouncement'),
    path('edit/<int:code>/<int:id>/',
         views.editAnnouncement, name='editAnnouncement'),
    path('update/<int:code>/<int:id>/',
         views.updateAnnouncement, name='updateAnnouncement'),
    path('addAssignment/<int:code>/', views.addAssignment, name='addAssignment'),
    path('assignment/<int:code>/<int:id>/',
         views.assignmentPage, name='assignmentPage'),
    path('assignments/<int:code>/', views.allAssignments, name='allAssignments'),
    path('siswa-assignments/<int:code>/',
         views.allAssignmentsSTD, name='siswa-assignments'),
    path('addSubmission/<int:code>/<int:id>/',
         views.addSubmission, name='addSubmission'),
    path('submission/<int:code>/<int:id>/',
         views.viewSubmission, name='submission'),
    path('gradeSubmission/<int:code>/<int:id>/<int:sub_id>',
         views.gradeSubmission, name='gradeSubmission'),
    path('jenjang-material/<int:code>/',
         views.addJenjangMaterial, name='addJenjangMaterial'),
    path('jenjang-material/<int:code>/<int:id>/',
         views.deleteJenjangMaterial, name='deleteJenjangMaterial'),
    path('jenjangs/', views.jenjangs, name='jenjangs'),
    path('tahunajarans/', views.tahunajarans, name='tahunajarans'),
    path('access/<int:code>/', views.access, name='access'),
    path('changePasswordPrompt/', views.changePasswordPrompt,
         name='changePasswordPrompt'),
    path('changePhotoPrompt/', views.changePhotoPrompt, name='changePhotoPrompt'),
    path('changePassword/', views.changePassword, name='changePassword'),
    path('changePasswordPengasuh/', views.changePasswordPengasuh,
         name='changePasswordPengasuh'),
    path('changePhoto/', views.changePhoto, name='changePhoto'),
    path('changePhotoPengasuh/', views.changePhotoPengasuh,
         name='changePhotoPengasuh'),
    path('search/', views.search, name='search'),
    path('error/', views.error, name='error'),
]
