# Generated by Django 4.2.3 on 2023-07-26 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jenjang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.jenjang')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.siswa')),
            ],
        ),
    ]
